"""
Streamlit dashboard for the Nifty 50 Multi-Factor Stock Direction Model.

Run with:
    streamlit run streamlit_app.py

Reads whatever's already been generated by the pipeline:
    data_cache/features/master_features.parquet   (from pipeline/run_daily.py)
    data_cache/models/nifty50_direction_model.joblib
    data_cache/models/eval_artifacts.joblib         (from models/train.py)

If those files don't exist yet, the dashboard tells you which pipeline
step to run first instead of crashing.
"""
import joblib
import pandas as pd
import streamlit as st

from config.settings import FEATURES_DIR, MODELS_DIR
from viz.visualization import (
    plot_price_with_signals,
    plot_macd_with_signals,
    plot_rsi,
    plot_sentiment_timeline,
    plot_confusion_matrix,
    plot_feature_importance,
    plot_prediction_confidence,
)

st.set_page_config(page_title="Nifty 50 Sentiment Edge", layout="wide")


# --- Cached loaders ------------------------------------------------------------
@st.cache_data
def load_master_df():
    path = FEATURES_DIR / "master_features.parquet"
    if not path.exists():
        return None
    df = pd.read_parquet(path)
    df["Date"] = pd.to_datetime(df["Date"])
    return df


@st.cache_resource
def load_model_bundle():
    path = MODELS_DIR / "nifty50_direction_model.joblib"
    if not path.exists():
        return None
    return joblib.load(path)


@st.cache_resource
def load_eval_artifacts():
    path = MODELS_DIR / "eval_artifacts.joblib"
    if not path.exists():
        return None
    return joblib.load(path)


# --- Load data ------------------------------------------------------------------
master_df = load_master_df()
model_bundle = load_model_bundle()
eval_artifacts = load_eval_artifacts()

st.title("📈 Sentiment Edge — Nifty 50 Multi-Factor Dashboard")
st.caption("Technical + Fundamental + NLP Sentiment (FinBERT) → LightGBM next-day direction prediction")

if master_df is None:
    st.error(
        "No feature table found. Run `python -m pipeline.run_daily` first "
        "to fetch data and build `data_cache/features/master_features.parquet`."
    )
    st.stop()

tickers_available = sorted(master_df["Ticker"].unique())

# --- Sidebar ----------------------------------------------------------------
st.sidebar.header("Stock Selection")
ticker = st.sidebar.selectbox("Choose a Nifty 50 stock", tickers_available)

date_range = st.sidebar.slider(
    "Lookback window (days)", min_value=30, max_value=730, value=180, step=10,
)

stock_df = master_df[master_df["Ticker"] == ticker].sort_values("Date")
cutoff = stock_df["Date"].max() - pd.Timedelta(days=date_range)
stock_df_windowed = stock_df[stock_df["Date"] >= cutoff]

if stock_df_windowed.empty:
    st.warning(f"No data for {ticker} in the selected window.")
    st.stop()

latest_row = stock_df.iloc[-1]

# --- Top-level metrics row ----------------------------------------------------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Latest Close", f"₹{latest_row['Close']:.2f}")
col2.metric("RSI (14)", f"{latest_row['RSI']:.1f}" if pd.notna(latest_row["RSI"]) else "N/A")
sent = latest_row.get("sentiment_score")
col3.metric("Latest Sentiment", f"{sent:.2f}" if pd.notna(sent) else "N/A")

if model_bundle is not None:
    model, feature_cols = model_bundle["model"], model_bundle["feature_cols"]
    row_for_pred = stock_df.iloc[[-1]].copy()
    row_for_pred["Ticker"] = row_for_pred["Ticker"].astype("category")
    up_prob = model.predict_proba(row_for_pred[feature_cols])[:, 1][0]
    col4.metric("Predicted P(Up) — Next Day", f"{up_prob:.0%}",
                delta="Bullish" if up_prob > 0.5 else "Bearish")
else:
    col4.metric("Predicted P(Up)", "No model trained")

st.divider()

# --- Tabs ----------------------------------------------------------------------
tab_price, tab_sentiment, tab_fundamentals, tab_model = st.tabs(
    ["📊 Technical & Signals", "📰 Sentiment", "🏦 Fundamentals", "🎯 Model Performance"]
)

with tab_price:
    st.plotly_chart(plot_price_with_signals(stock_df_windowed, ticker), use_container_width=True)
    c1, c2 = st.columns(2)
    with c1:
        st.plotly_chart(plot_macd_with_signals(stock_df_windowed, ticker), use_container_width=True)
    with c2:
        st.plotly_chart(plot_rsi(stock_df_windowed, ticker), use_container_width=True)

with tab_sentiment:
    if "sentiment_score" in stock_df_windowed.columns and stock_df_windowed["sentiment_score"].notna().any():
        st.plotly_chart(plot_sentiment_timeline(stock_df_windowed, ticker), use_container_width=True)
    else:
        st.info("No sentiment data available for this ticker/window yet.")

with tab_fundamentals:
    fundamental_cols = [
        "PE_Ratio", "PB_Ratio", "ROE", "Debt_To_Equity", "Profit_Margin",
        "Revenue_Growth_YoY", "Earnings_Growth_YoY",
    ]
    available_cols = [c for c in fundamental_cols if c in stock_df.columns]
    if available_cols:
        latest_fundamentals = stock_df[available_cols].iloc[-1]
        st.dataframe(latest_fundamentals.rename("Value").to_frame(), use_container_width=True)
    else:
        st.info("No fundamental data available for this ticker yet.")

with tab_model:
    if eval_artifacts is None:
        st.warning("No evaluation artifacts found. Run `python -m models.train` to generate them.")
    else:
        c1, c2 = st.columns(2)
        c1.metric("Test-Set Accuracy", f"{eval_artifacts['accuracy']:.1%}")
        c2.caption(f"Chronological split cutoff date: {eval_artifacts['cutoff_date']}")

        st.plotly_chart(plot_confusion_matrix(eval_artifacts["confusion_matrix"]), use_container_width=True)
        st.plotly_chart(plot_feature_importance(eval_artifacts["feature_importances"]), use_container_width=True)

        st.subheader(f"Predicted vs. Actual — {ticker} (test period only)")
        preds = eval_artifacts["predictions_df"]
        if ticker in preds["Ticker"].unique():
            st.plotly_chart(plot_prediction_confidence(preds, ticker), use_container_width=True)
        else:
            st.info(f"{ticker} has no rows in the test period (may fall entirely in the training window).")
